name: taskly
services:
  databases:
    image: postgres
    container_name: databases
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./databases/pgdata:/data/postgres
      - ./databases/init:/docker-entrypoint-initdb.d

  taskly-api:
    build: .
    container_name: taskly-api
    restart: unless-stopped
    ports:
      - 3001:3001
    depends_on:
      - databases
    volumes:
      - .:/usr/src/app
